### lecture 70 D =19-10-22

# PROJECT

## lecture 71 D =20-10-22

In [1]:
import pandas as pd 
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,mean_absolute_error,r2_score,mean_squared_error

In [3]:
df=pd.read_csv("medical insurance.csv")

df.head()

age  gender        bmi  children smoker     region       charges
0  21.000000    male  25.745000         2     no  northeast   3279.868550
1  36.976978  female  25.744165         3    yes  southeast  21454.494240
2  18.000000    male  30.030000         1     no  southeast   1720.353700
3  37.000000    male  30.676891         3     no  northeast   6801.437542
4  58.000000    male  32.010000         1     no  southeast  11946.625900

In [4]:
df.isna().sum()

age         0
gender      0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3630 entries, 0 to 3629
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       3630 non-null   float64
 1   gender    3630 non-null   object 
 2   bmi       3630 non-null   float64
 3   children  3630 non-null   int64  
 4   smoker    3630 non-null   object 
 5   region    3630 non-null   object 
 6   charges   3630 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 198.6+ KB


In [7]:
df["gender"].unique()

array(['male', 'female'], dtype=object)

In [8]:
df["gender"].value_counts()

gender
male      2029
female    1601
Name: count, dtype: int64

In [10]:
df["gender"].replace({"female":0,"male":1},inplace=True)


In [11]:
df["smoker"].value_counts()

smoker
no     3070
yes     560
Name: count, dtype: int64

In [14]:
df["smoker"].replace({"no":0,"yes":1},inplace=True)


In [13]:
df["region"].value_counts()

region
southeast    1021
northwest     911
southwest     850
northeast     848
Name: count, dtype: int64

In [15]:
#replace columns
#get_dummies
df=pd.get_dummies(df,columns=['region'])
df

age  gender        bmi  children  smoker       charges  \
0     21.000000       1  25.745000         2       0   3279.868550   
1     36.976978       0  25.744165         3       1  21454.494240   
2     18.000000       1  30.030000         1       0   1720.353700   
3     37.000000       1  30.676891         3       0   6801.437542   
4     58.000000       1  32.010000         1       0  11946.625900   
...         ...     ...        ...       ...     ...           ...   
3625  48.820767       0  41.426984         4       0  10987.324960   
3626  38.661977       0  26.202557         2       0  11735.844350   
3627  56.000000       1  40.300000         0       0  10602.385000   
3628  48.061207       0  34.930624         1       0   8976.140452   
3629  37.598865       0  25.219233         3       0   7027.698968   

      region_northeast  region_northwest  region_southeast  region_southwest  
0                 True             False             False             False  
1                False             False              True             False  
2                False             False              True             False  
3                 True             False             False             False  
4                False             False              True             False  
...                ...               ...               ...               ...  
3625             False              True             False             False  
3626             False             False              True             False  
3627             False             False             False              True  
3628             False             False              True             False  
3629              True             False             False             False  

[3630 rows x 10 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3630 entries, 0 to 3629
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               3630 non-null   float64
 1   gender            3630 non-null   int64  
 2   bmi               3630 non-null   float64
 3   children          3630 non-null   int64  
 4   smoker            3630 non-null   int64  
 5   charges           3630 non-null   float64
 6   region_northeast  3630 non-null   bool   
 7   region_northwest  3630 non-null   bool   
 8   region_southeast  3630 non-null   bool   
 9   region_southwest  3630 non-null   bool   
dtypes: bool(4), float64(3), int64(3)
memory usage: 184.5 KB


In [17]:
df['children'].value_counts()

children
0    619
2    615
5    610
3    605
4    604
1    577
Name: count, dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3630 entries, 0 to 3629
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               3630 non-null   float64
 1   gender            3630 non-null   int64  
 2   bmi               3630 non-null   float64
 3   children          3630 non-null   int64  
 4   smoker            3630 non-null   int64  
 5   charges           3630 non-null   float64
 6   region_northeast  3630 non-null   bool   
 7   region_northwest  3630 non-null   bool   
 8   region_southeast  3630 non-null   bool   
 9   region_southwest  3630 non-null   bool   
dtypes: bool(4), float64(3), int64(3)
memory usage: 184.5 KB


## train_test_split

In [19]:
x=df.drop("charges",axis=1)
y=df["charges"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=45)


In [20]:

x_train

age  gender        bmi  children  smoker  region_northeast  \
1167  41.653559       1  25.932576         3       1             False   
505   33.633773       0  32.001339         3       0             False   
3343  49.080885       0  26.663563         4       0             False   
478   27.000000       1  18.905000         3       0              True   
81    24.371038       1  26.033838         5       0             False   
...         ...     ...        ...       ...     ...               ...   
3616  49.269800       0  34.402817         4       0             False   
1916  38.661977       0  26.202557         2       0             False   
1667  53.458139       0  29.078313         2       0              True   
2462  20.000000       0  24.420000         0       1             False   
3019  39.000000       1  30.281625         5       0             False   

      region_northwest  region_southeast  region_southwest  
1167             False              True             False  
505              False              True             False  
3343              True             False             False  
478              False             False             False  
81               False             False              True  
...                ...               ...               ...  
3616              True             False             False  
1916             False              True             False  
1667             False             False             False  
2462             False              True             False  
3019             False              True             False  

[2904 rows x 9 columns]

## model_training

In [21]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

## testing_data_evaluation

In [22]:
y_pred=model.predict(x_test)

mse=mean_squared_error(y_test,y_pred)
print("MSE IS:",mse)

rmse=np.sqrt(mse)
print("RMSE IS:",rmse)

mae=mean_absolute_error(y_test,y_pred)
print("MAE IS :",mae)

r2=r2_score(y_test,y_pred)
print("r2_score is :",r2)

MSE IS: 29664506.90421684
RMSE IS: 5446.513279541035
MAE IS : 3626.53008990654
r2_score is : 0.729195687083924


## training_data_evaluation


In [23]:
y_pred_train=model.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print("MSE IS:",mse)

rmse=np.sqrt(mse)
print("RMSE IS:",rmse)

mae=mean_absolute_error(y_train,y_pred_train)
print("MAE IS :",mae)

r2=r2_score(y_train,y_pred_train)
print("r2_score is :",r2)

MSE IS: 33155815.414538864
RMSE IS: 5758.108666440645
MAE IS : 3890.088016869372
r2_score is : 0.7163356931287135


## testing on single row

In [24]:
x.head(1).T

0
age                 21.0
gender                 1
bmi               25.745
children               2
smoker                 0
region_northeast    True
region_northwest   False
region_southeast   False
region_southwest   False

age	=35
gender ="male"
bmi =105	
children = 2
smoker = "yes"

region ="southwest"


In [25]:
column_names=x.columns
column_names

Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

### test array

In [28]:
test_array=np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
label_encoded_data={"gender":{"female":0,"male":1},
                    "smoker":{"no":0,"yes":1}
                   }

label_encoded_data["smoker"][smoker]
label_encoded_data["gender"][gender]

0

In [39]:
region="region_"+ region
region

'region_southwest'

In [40]:
region_index=np.where(column_names ==region)[0][0]
region_index

np.int64(8)

In [41]:
test_array[0]=age
test_array[1]=label_encoded_data["gender"][gender]
test_array[2]=bmi
test_array[3]=children
test_array[4]=label_encoded_data["smoker"][smoker]
test_array[region_index]=1

In [151]:
test_array

array([40. ,  0. , 26.5,  3. ,  0. ,  0. ,  0. ,  0. ,  1. ])

In [37]:
age	=40
gender ="female"
bmi =26.5
children = 3
smoker = "no"

region ="southwest"


In [42]:
model.predict([test_array])

C:\Users\dhama\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7268.54915829])

In [43]:
import pickle
with open("linear_model.pkl","wb") as f:
    pickle.dump(model,f)

In [44]:
project_data={"gender":{"female":0,"male":1},
                    "smoker":{"no":0,"yes":1},
                    "columns":list(x.columns) }


In [45]:
import json
with open("project_data.json","w")as f:
    json.dump(project_data,f)